namespace Model
{
    public enum Food
    {
        [SomeString("Yummy!")]
        Pizza,
        
        [SomeString("Well...")]
        Kale,
    }

    public enum WarhammerFigurine
    {
        [SomeString("For the Emperor!")]
        SpaceMarine,
        
        [SomeString("For the Greater Good!")]
        FireWarrior
    }

    public enum Pokemon
    {
        [SomeString("Bulbasaur")]
        Bulbasaur,
        [SomeString("Ivysaur")]
        Ivysaur,
        [SomeString("Venusaur")]
        Venusaur,
        [SomeString("Charmander")]
        Charmander,
        [SomeString("Charmeleon")]
        Charmeleon,
        [SomeString("Charizard")]
        Charizard,
        [SomeString("Squirtle")]
        Squirtle,
        [SomeString("Wartortle")]
        Wartortle,
        [SomeString("Blastoise")]
        Blastoise,
        [SomeString("Caterpie")]
        Caterpie,
        [SomeString("Metapod")]
        Metapod,
        [SomeString("Butterfree")]
        Butterfree,
        [SomeString("Weedle")]
        Weedle,
        [SomeString("Kakuna")]
        Kakuna,
        [SomeString("Beedrill")]
        Beedrill,
        [SomeString("Pidgey")]
        Pidgey,
        [SomeString("Pidgeotto")]
        Pidgeotto,
        [SomeString("Pidgeot")]
        Pidgeot,
        [SomeString("Rattata")]
        Rattata,
        [SomeString("Raticate")]
        Raticate,
        [SomeString("Spearow")]
        Spearow,
        [SomeString("Fearow")]
        Fearow,
        [SomeString("Ekans")]
        Ekans,
        [SomeString("Arbok")]
        Arbok,
        [SomeString("Pikachu")]
        Pikachu,
        [SomeString("Raichu")]
        Raichu,
        [SomeString("Sandshrew")]
        Sandshrew,
        [SomeString("Sandslash")]
        Sandslash,
        [SomeString("Nidorina")]
        Nidorina,
        [SomeString("Nidoqueen")]
        Nidoqueen,
        [SomeString("Nidorino")]
        Nidorino,
        [SomeString("Nidoking")]
        Nidoking,
        [SomeString("Clefairy")]
        Clefairy,
        [SomeString("Clefable")]
        Clefable,
        [SomeString("Vulpix")]
        Vulpix,
        [SomeString("Ninetales")]
        Ninetales,
        [SomeString("Jigglypuff")]
        Jigglypuff,
        [SomeString("Wigglytuff")]
        Wigglytuff,
        [SomeString("Zubat")]
        Zubat,
        [SomeString("Golbat")]
        Golbat,
        [SomeString("Oddish")]
        Oddish,
        [SomeString("Gloom")]
        Gloom,
        [SomeString("Vileplume")]
        Vileplume,
        [SomeString("Paras")]
        Paras,
        [SomeString("Parasect")]
        Parasect,
        [SomeString("Venonat")]
        Venonat,
        [SomeString("Venomoth")]
        Venomoth,
        [SomeString("Diglett")]
        Diglett,
        [SomeString("Dugtrio")]
        Dugtrio,
        [SomeString("Meowth")]
        Meowth,
        [SomeString("Persian")]
        Persian,
        [SomeString("Psyduck")]
        Psyduck,
        [SomeString("Golduck")]
        Golduck,
        [SomeString("Mankey")]
        Mankey,
        [SomeString("Primeape")]
        Primeape,
        [SomeString("Growlithe")]
        Growlithe,
        [SomeString("Arcanine")]
        Arcanine,
        [SomeString("Poliwag")]
        Poliwag,
        [SomeString("Poliwhirl")]
        Poliwhirl,
        [SomeString("Poliwrath")]
        Poliwrath,
        [SomeString("Abra")]
        Abra,
        [SomeString("Kadabra")]
        Kadabra,
        [SomeString("Alakazam")]
        Alakazam,
        [SomeString("Machop")]
        Machop,
        [SomeString("Machoke")]
        Machoke,
        [SomeString("Machamp")]
        Machamp,
        [SomeString("Bellsprout")]
        Bellsprout,
        [SomeString("Weepinbell")]
        Weepinbell,
        [SomeString("Victreebel")]
        Victreebel,
        [SomeString("Tentacool")]
        Tentacool,
        [SomeString("Tentacruel")]
        Tentacruel,
        [SomeString("Geodude")]
        Geodude,
        [SomeString("Graveler")]
        Graveler,
        [SomeString("Golem")]
        Golem,
        [SomeString("Ponyta")]
        Ponyta,
        [SomeString("Rapidash")]
        Rapidash,
        [SomeString("Slowpoke")]
        Slowpoke,
        [SomeString("Slowbro")]
        Slowbro,
        [SomeString("Magnemite")]
        Magnemite,
        [SomeString("Magneton")]
        Magneton,
        [SomeString("Doduo")]
        Doduo,
        [SomeString("Dodrio")]
        Dodrio,
        [SomeString("Seel")]
        Seel,
        [SomeString("Dewgong")]
        Dewgong,
        [SomeString("Grimer")]
        Grimer,
        [SomeString("Muk")]
        Muk,
        [SomeString("Shellder")]
        Shellder,
        [SomeString("Cloyster")]
        Cloyster,
        [SomeString("Gastly")]
        Gastly,
        [SomeString("Haunter")]
        Haunter,
        [SomeString("Gengar")]
        Gengar,
        [SomeString("Onix")]
        Onix,
        [SomeString("Drowzee")]
        Drowzee,
        [SomeString("Hypno")]
        Hypno,
        [SomeString("Krabby")]
        Krabby,
        [SomeString("Kingler")]
        Kingler,
        [SomeString("Voltorb")]
        Voltorb,
        [SomeString("Electrode")]
        Electrode,
        [SomeString("Exeggcute")]
        Exeggcute,
        [SomeString("Exeggutor")]
        Exeggutor,
        [SomeString("Cubone")]
        Cubone,
        [SomeString("Marowak")]
        Marowak,
        [SomeString("Hitmonlee")]
        Hitmonlee,
        [SomeString("Hitmonchan")]
        Hitmonchan,
        [SomeString("Lickitung")]
        Lickitung,
        [SomeString("Koffing")]
        Koffing,
        [SomeString("Weezing")]
        Weezing,
        [SomeString("Rhyhorn")]
        Rhyhorn,
        [SomeString("Rhydon")]
        Rhydon,
        [SomeString("Chansey")]
        Chansey,
        [SomeString("Tangela")]
        Tangela,
        [SomeString("Kangaskhan")]
        Kangaskhan,
        [SomeString("Horsea")]
        Horsea,
        [SomeString("Seadra")]
        Seadra,
        [SomeString("Goldeen")]
        Goldeen,
        [SomeString("Seaking")]
        Seaking,
        [SomeString("Staryu")]
        Staryu,
        [SomeString("Starmie")]
        Starmie,
        [SomeString("Scyther")]
        Scyther,
        [SomeString("Jynx")]
        Jynx,
        [SomeString("Electabuzz")]
        Electabuzz,
        [SomeString("Magmar")]
        Magmar,
        [SomeString("Pinsir")]
        Pinsir,
        [SomeString("Tauros")]
        Tauros,
        [SomeString("Magikarp")]
        Magikarp,
        [SomeString("Gyarados")]
        Gyarados,
        [SomeString("Lapras")]
        Lapras,
        [SomeString("Ditto")]
        Ditto,
        [SomeString("Eevee")]
        Eevee,
        [SomeString("Vaporeon")]
        Vaporeon,
        [SomeString("Jolteon")]
        Jolteon,
        [SomeString("Flareon")]
        Flareon,
        [SomeString("Porygon")]
        Porygon,
        [SomeString("Omanyte")]
        Omanyte,
        [SomeString("Omastar")]
        Omastar,
        [SomeString("Kabuto")]
        Kabuto,
        [SomeString("Kabutops")]
        Kabutops,
        [SomeString("Aerodactyl")]
        Aerodactyl,
        [SomeString("Snorlax")]
        Snorlax,
        [SomeString("Articuno")]
        Articuno,
        [SomeString("Zapdos")]
        Zapdos,
        [SomeString("Moltres")]
        Moltres,
        [SomeString("Dratini")]
        Dratini,
        [SomeString("Dragonair")]
        Dragonair,
        [SomeString("Dragonite")]
        Dragonite,
        [SomeString("Mewtwo")]
        Mewtwo,
        [SomeString("Mew")]
        Mew,
    }
}