using SourceGeneratorTest;

namespace Model
{
    [ToJson]
    public partial struct PokemonList
    {
        public int Bulbasaur { get; set; }
        public int Ivysaur { get; set; }
        public int Venusaur { get; set; }
        public int Charmander { get; set; }
        public int Charmeleon { get; set; }
        public int Charizard { get; set; }
        public int Squirtle { get; set; }
        public int Wartortle { get; set; }
        public int Blastoise { get; set; }
        public int Caterpie { get; set; }
        public int Metapod { get; set; }
        public int Butterfree { get; set; }
        public int Weedle { get; set; }
        public int Kakuna { get; set; }
        public int Beedrill { get; set; }
        public int Pidgey { get; set; }
        public int Pidgeotto { get; set; }
        public int Pidgeot { get; set; }
        public int Rattata { get; set; }
        public int Raticate { get; set; }
        public int Spearow { get; set; }
        public int Fearow { get; set; }
        public int Ekans { get; set; }
        public int Arbok { get; set; }
        public int Pikachu { get; set; }
        public int Raichu { get; set; }
        public int Sandshrew { get; set; }
        public int Sandslash { get; set; }
        public int Nidorina { get; set; }
        public int Nidoqueen { get; set; }
        public int Nidorino { get; set; }
        public int Nidoking { get; set; }
        public int Clefairy { get; set; }
        public int Clefable { get; set; }
        public int Vulpix { get; set; }
        public int Ninetales { get; set; }
        public int Jigglypuff { get; set; }
        public int Wigglytuff { get; set; }
        public int Zubat { get; set; }
        public int Golbat { get; set; }
        public int Oddish { get; set; }
        public int Gloom { get; set; }
        public int Vileplume { get; set; }
        public int Paras { get; set; }
        public int Parasect { get; set; }
        public int Venonat { get; set; }
        public int Venomoth { get; set; }
        public int Diglett { get; set; }
        public int Dugtrio { get; set; }
        public int Meowth { get; set; }
        public int Persian { get; set; }
        public int Psyduck { get; set; }
        public int Golduck { get; set; }
        public int Mankey { get; set; }
        public int Primeape { get; set; }
        public int Growlithe { get; set; }
        public int Arcanine { get; set; }
        public int Poliwag { get; set; }
        public int Poliwhirl { get; set; }
        public int Poliwrath { get; set; }
        public int Abra { get; set; }
        public int Kadabra { get; set; }
        public int Alakazam { get; set; }
        public int Machop { get; set; }
        public int Machoke { get; set; }
        public int Machamp { get; set; }
        public int Bellsprout { get; set; }
        public int Weepinbell { get; set; }
        public int Victreebel { get; set; }
        public int Tentacool { get; set; }
        public int Tentacruel { get; set; }
        public int Geodude { get; set; }
        public int Graveler { get; set; }
        public int Golem { get; set; }
        public int Ponyta { get; set; }
        public int Rapidash { get; set; }
        public int Slowpoke { get; set; }
        public int Slowbro { get; set; }
        public int Magnemite { get; set; }
        public int Magneton { get; set; }
        public int Doduo { get; set; }
        public int Dodrio { get; set; }
        public int Seel { get; set; }
        public int Dewgong { get; set; }
        public int Grimer { get; set; }
        public int Muk { get; set; }
        public int Shellder { get; set; }
        public int Cloyster { get; set; }
        public int Gastly { get; set; }
        public int Haunter { get; set; }
        public int Gengar { get; set; }
        public int Onix { get; set; }
        public int Drowzee { get; set; }
        public int Hypno { get; set; }
        public int Krabby { get; set; }
        public int Kingler { get; set; }
        public int Voltorb { get; set; }
        public int Electrode { get; set; }
        public int Exeggcute { get; set; }
        public int Exeggutor { get; set; }
        public int Cubone { get; set; }
        public int Marowak { get; set; }
        public int Hitmonlee { get; set; }
        public int Hitmonchan { get; set; }
        public int Lickitung { get; set; }
        public int Koffing { get; set; }
        public int Weezing { get; set; }
        public int Rhyhorn { get; set; }
        public int Rhydon { get; set; }
        public int Chansey { get; set; }
        public int Tangela { get; set; }
        public int Kangaskhan { get; set; }
        public int Horsea { get; set; }
        public int Seadra { get; set; }
        public int Goldeen { get; set; }
        public int Seaking { get; set; }
        public int Staryu { get; set; }
        public int Starmie { get; set; }
        public int Scyther { get; set; }
        public int Jynx { get; set; }
        public int Electabuzz { get; set; }
        public int Magmar { get; set; }
        public int Pinsir { get; set; }
        public int Tauros { get; set; }
        public int Magikarp { get; set; }
        public int Gyarados { get; set; }
        public int Lapras { get; set; }
        public int Ditto { get; set; }
        public int Eevee { get; set; }
        public int Vaporeon { get; set; }
        public int Jolteon { get; set; }
        public int Flareon { get; set; }
        public int Porygon { get; set; }
        public int Omanyte { get; set; }
        public int Omastar { get; set; }
        public int Kabuto { get; set; }
        public int Kabutops { get; set; }
        public int Aerodactyl { get; set; }
        public int Snorlax { get; set; }
        public int Articuno { get; set; }
        public int Zapdos { get; set; }
        public int Moltres { get; set; }
        public int Dratini { get; set; }
        public int Dragonair { get; set; }
        public int Dragonite { get; set; }
        public int Mewtwo { get; set; }
        public int Mew { get; set; }
    }
}